channels:
- conda-forge
dependencies:
- python=3.12.12
- pip<=25.3
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.2
  - numpy==2.1.3
  - pandas==2.2.3
  - psutil==7.1.3
  - scikit-learn==1.5.2
  - scipy==1.14.1
  - mlflow==2.19.0
name: mlflow-env